# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Changes

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi

    - name: Test python source code
      run: nosetests --v petl --with-coverage --cover-package=petl

    - name: Test documentation inside source code
      run: nosetests -v --with-doctest --doctest-options=+NORMALIZE_WHITESPACE petl -I"csv_py2\.py" -I"db\.py"

    - name: Install doc generation dependencies
      run: |
        if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; fi

    - name: Test docs generation
      run: sphinx-build -W -b singlehtml -d build/doctrees .  build/singlehtml

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # path-to-lcov: './lcov.info'
